package com.shenjianli.fly.app.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.shenjianli.fly.model.LocEntity;

import com.shenjianli.fly.app.db.LocEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig locEntityDaoConfig;

    private final LocEntityDao locEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        locEntityDaoConfig = daoConfigMap.get(LocEntityDao.class).clone();
        locEntityDaoConfig.initIdentityScope(type);

        locEntityDao = new LocEntityDao(locEntityDaoConfig, this);

        registerDao(LocEntity.class, locEntityDao);
    }
    
    public void clear() {
        locEntityDaoConfig.clearIdentityScope();
    }

    public LocEntityDao getLocEntityDao() {
        return locEntityDao;
    }

}
